### ISSUE TITLE
Compilation in vs code (not build)

### ISSUE THREAD

**Issue by ThatLuckyDay** [github0null/stm8-debug#5]
Please tell me if there is a possibility to compile the project? 
I am using your plugin in conjunction with cosmic.

**Comment by github0null** [comment]
sorry ! it's only a debugger, which has not compilation support

If you use SDCC or IAR-For-STM8, I also have another plug-in: Embeded IDE, it's support SDCC and IAR-STM8-Toolchain

**Comment by ThatLuckyDay** [comment]
Ok. Thank you for your help!
